DWAPlannerROS:
  max_trans_vel: 0.5
  min_trans_vel: 0.01
  max_vel_x: 0.5
  min_vel_x: -0.025
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 0.3
  min_rot_vel: -0.30 # if no sensor in the back of the robot we will turn it off  
  acc_lim_x: 1.25
  acc_lim_y: 0.0
  acc_lim_theta: 5.0
  acc_lim_trans: 1.25

  prune_plan: false

  xy_goal_tolerance: 0.25 # it will turn and move about the goal trying to reach it with this tolerance
  yaw_goal_tolerance: 0.1
  trans_stopped_vel: 0.1
  rot_stopped_vel: 0.1
  # time to simulate the trajectory and get a cost for it 
  sim_time: 3.0
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  path_distance_bias: 34.0 # how much it should care about the path distance
  goal_distance_bias: 24.0 
  occdist_scale: 0.05
  twirling_scale: 0.0
  stop_time_buffer: 0.5
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2
  forward_point_distance: 0.3
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  # the number of samples to use when exploring the space of trajectories
  # the more samples, the more accurate the result will be, but it will take longer to compute
  #the DWA create a lot of samples and choose the best one
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40

  use_dwa: true
  restore_defaults: false
