# is simply as a rectangle around the robot with a specified width, height, and resolution. to avoid the obstacles
local_costmap:

  global_frame: odom #because it is the local costmap and it is based on the robot's odometry
  robot_base_frame: robot_footprint
  update_frequency: 5.0 #before 5.0
  publish_frequency: 7.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05 #increase to for higher res 0.025
  transform_tolerance: 0.5
  cost_scaling_factor: 5
  inflation_radius: 0.55